server:
  http:
    addr: 0.0.0.0:8998
    timeout: 1s
  grpc:
    addr: 0.0.0.0:8999
    timeout: 1s
data:
  database:
    driver: mysql
    source: bitstorm-svr-go-root:YfxGpMkPWYfEi87K@tcp(59.110.34.61:3306)/bitstorm-svr-go
  redis:
    addr: 59.110.34.61:6379
    db: 8
    passWord: xiwanli
    read_timeout: 2s
    write_timeout: 2s

micro:
  lb:
    addr: 59.110.34.61:20002
    disSvrList: ["user-svr", "sec_kill-svr","lottery-svr","xtimer-svr"]
